FROM python:2.7

ENV PYTHONBUFFERED 1

RUN mkdir /code
RUN mkdir /logs
WORKDIR /code

ADD requirements.txt /code/

RUN pip install -r requirements.txt
ADD . /code/
RUN python manage.py migrate
RUN python manage.py loaddata initial.json
