# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='nome',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Nome da rota'),
        ),
    ]
